INSERT INTO Tb_base_user (name, email) VALUES ('Carlos', 'kainaquirino@gamil.com')
INSERT INTO Tb_adimin (phone_number, baseuser_id) VALUES ('(15) 99861-5601', '1')
INSERT INTO Tb_event (name, description, start_date, end_date, start_time, end_time, email_contact, amount_free_tickets, amount_payed_tickets, price_ticket, admin_id) VALUES ('Toy Story', 'Apresentação de teatro infantil', '2021-04-12', '2021-04-12', '16:00:00', '18:00:00', 'toyStory@gmail.com', '15', '30', '15.00', '1')
INSERT INTO Tb_place (name, address) VALUES ('praça de ventos', '31 de março - Votorantim')
INSERT INTO Tb_base_user (name, email) VALUES ('Rafa', 'RafaOLiveira@gamil.com')
INSERT INTO Tb_attendee (balance, baseuser_id) VALUES ('50.00', '2')

INSERT INTO Tb_base_user (name, email) VALUES ('Ramon', 'RamonFrias@gamil.com')
INSERT INTO Tb_adimin (phone_number, baseuser_id) VALUES ('(15) 99871-6602', '3')
INSERT INTO Tb_event (name, description, start_date, end_date, start_time, end_time, email_contact, amount_free_tickets, amount_payed_tickets, price_ticket, admin_id) VALUES ('Infinit', 'Balada - show ALOK', '2021-05-02', '2021-05-03', '23:00:00', '05:00:00', 'InfintiHall@gmail.com', '0', '350', '10.00', '3')
INSERT INTO Tb_place (name, address) VALUES ('Infinity Hall', 'Sorocaba - perto da prefeitura')
INSERT INTO Tb_base_user (name, email) VALUES ('Joao', 'Joao.GamePlay@gamil.com')
INSERT INTO Tb_attendee (balance, baseuser_id) VALUES ('500.00', '4')

INSERT INTO Tb_base_user (name, email) VALUES ('Jose', 'JoseRamalho@gamil.com')
INSERT INTO Tb_adimin (phone_number, baseuser_id) VALUES ('(51) 99461-1194', '5')
INSERT INTO Tb_event (name, description, start_date, end_date, start_time, end_time, email_contact, amount_free_tickets, amount_payed_tickets, price_ticket, admin_id) VALUES ('Magic', 'show de magica - onde a magia acontece', '2020-04-12', '2020-04-14', '19:30:00', '21:30:00', 'Magic@gmail.com', '150', '0', '00.00', '5')
INSERT INTO Tb_place (name, address) VALUES ('praça de ventos', '31 de março - Votorantim')
INSERT INTO Tb_base_user (name, email) VALUES ('Kaina', 'KAina@gamil.com')
INSERT INTO Tb_attendee (balance, baseuser_id) VALUES ('150.00', '6')

INSERT INTO Tb_event_place (place_id, event_id) VALUES ('1', '2')

INSERT INTO Tb_ticket (Type, date, price, event_id, atendee_id) VALUES ('0', '2021-05-02', '0.00', '1', '2')
INSERT INTO Tb_ticket (Type, date, price, event_id, atendee_id) VALUES ('1', '2021-05-02', '150.50', '1', '2')
